//
//  CardManager.swift
//  Penisland
//
//  Created by Dan Patey on 5/26/16.
//  Copyright © 2016 Dan Patey. All rights reserved.
//

import UIKit
import Foundation

class CardManager: NSObject {
    static let card1 = Card(title: "1) The Toast", rule_description: "\"Cheers to the last time we will all be friends!\" The Roller must start the game off by proposing a group toast.", rules: nil, image: UIImage(named: "the_toast.png")!)
    
    static let card2 = Card(title: "2) Name Master", rule_description: "The Roller must assign each player with a new name (or draw random below) to replace everyone's lame birth names. They may enforce these names for the remainder of the game by handing out the Loser Penalty to anyone who forgets to use them."
        , rules: [
            "Everyone is \"Peasant\"",
            "Everyone is \"Vin Diesel\"",
            "Everyone is a type of Jungle Animal (as determined by the Name Master)",
            "Everyone is a different Reality TV Star. Go around the circle to introduce yourselves.",
            "Everyone is a Past President. Go around the circle to introduce yourselves.",
            "Everyone must take the name of the person to their left",
            "Everyone must take the name of their first pet. Go around the circle to introduce yourselves.",
            "Everyone is \"Bro\"/\"Lady Bro\"",
            "Everyone is \"Mr.\" / \"Miss\" plus their First Name (example: Mr. Billy)",
            "Everyone is \"Senior\" / \"Seniorita\" & their Last Name (example: Seniorita Johnson)",
            "Everyone is a different Fast Food Chain (examples: \"Wendy\", \"Carl Jr.\", \"Burger King\"). Go around the circle to introduce yourselves.",
            "Everyone is \"Chief\"",
            "All guys are \"Daddy\"; All girls are \"Mama\"",
            "Everyone is \"Sweetie\"",
            "Everyone is \"Sugar-tits\"",
            "The Name Master must give everyone a stripper name",
            "Everyone is the name of their sexiest body part (as determined by the Name Master)",
            "Everyone is \"Lil\" plus their first name (example: Lil Steve)",
            "Everyone is \"Big\" plus their first name (example: Big Tina)",
            "Everyone is \"Fat\" plus their first name (example: Fat Tiffany)",
            "Everyone is \"Sir\" / \"Madam\" plus their first name and their birthplace (example: Sir Tobin of Omaha). Go around the circle to introduce yourselves.",
            "Everyone is \"Dr.\" plus their last name",
            "Everyone is \"Your Honor\"",
            "Everyone is a Little Rascal (Alfalfa, Spanky, Darla, Porky, Froggy, Uh-huh, Waldo, Buckwheat)"], image: UIImage(named: "name_master.png")!)
    
    static let card3 = Card(title: "3) Beverage Butler", rule_description: "Just like in one of them super fancy restaurants that give you free bread and cloth napkins, The Roller must provide all players with beverages when ordered for the remainder of the game. If non-compliant, the Beverage Butler shall be banished from the game forever. No tips required.", rules: nil, image: UIImage(named: "beverage_butler.png")!)
    
    static let card4 = Card(title: "4) President Trump", rule_description: "Despite being woefully unqualified, The Roller has just become the President of the game. This means they have the authority to resolve any and all disputes, over-rule the Loser Penalty with whatever they see fit, and generally make enemies with everyone that crosses their path. They may also appoint a Vice President to \"aid\" in decision making (though this is obviously just a mere formality). Gonna be a long game with this asshole at the helm...", rules: nil, image: UIImage(named: "president_trump.png")!)
    
    static let card5 = Card(title: "5) Snapchat Paparazzi", rule_description: "The Roller must secretly capture their opponents doing something weird on Snapchat at some point during the game (there should be plenty of opportunities). If you're the type of person that doesn't have a Snapchat, you can simply go get your photos developed at the local pharmacy after the game and then mail them out to every contact in your phonebook. Just be sure to include an airtight contract that the photos must be destroyed after 24 hours so nothing scandalous winds up in the tabloids.", rules: nil, image: UIImage(named: "snapchat_paparazzi.png")!)
    
    static let card6 = Card(title: "6) The Sneaky Texter", rule_description: "The Roller now has the ability to text anyone in the game, at any time, a number from 1-5. If a person receives one of these messages from the Sneaky Texter, they are subject to the Loser Penalty times the number received in the text. However, if the Sneaky Texter is caught in the act of texting by any player in the game, they are immediately subject to triple the Loser Penalty. Everyone should constantly have their eye on this fast-fingered weasel.", rules: nil, image: UIImage(named: "the_sneaky_texter.png")!)
    
    static let card7 = Card(title: "7) Make A Rule", rule_description: "The Roller may make a rule in which all players must follow. Violators of this sacred law shall be subject to public execution (or the Loser Penalty).", rules: nil, image: UIImage(named: "make_a_rule.png")!)
    
    static let card8 = Card(title: "8) Tunes Master", rule_description: "Sorry guys, like a cut-rate wedding DJ hired off craigslist, The Roller gets to impose their shitty music on everyone for the remainder of the game (keep in mind that if it gets too bad there are Pen Island playlists available on Spotify @ thepenislandgame).", rules: nil, image: UIImage(named: "tunes_master.png")!)
    
    static let card9 = Card(title: "9) Bad Categories", rule_description: "Group Game - The Roller will draw a random Bad Category below. Beginning with person to The Roller's left, all players must say a relevant answer. No repeats. 1st player to mess up is subject to double the Loser Penalty.", rules: [
        "Things that Boobs feel like",
        "Names of People you've made out with",
        "Things that resemble a penis",
        "Places you wouldn't want to be caught having sex",
        "Places you wouldn't want to be caught looking at porn",
        "Places you wouldn't want to take a dump",
        "Alternative names for \"Oral Sex\"",
        "Alternative names for \"Jerking Off\"",
        "Things that could theoretically get stuck up your butt",
        "Things you could use instead of toilet paper",
        "Things that are sticky",
        "Things that are moist",
        "Bad occasions to get really drunk",
        "Alternative ways to say \"Passing Gas\"",
        "Names of Shitty Universities",
        "Names of Fat Celebrities",
        "Underrated Sex Positions",
        "Stripper Names",
        "Bad Things to Say After Sex",
        "Bad Pick-up Lines",
        "Things that Smell Bad",
        "Things that Make You Sweaty",
        "Wacky Religions",
        "Restaurants You Wouldn't be Caught Dead In",
        "Places you've hooked up",
        "Celebs you would bang",
        "Things you would do to get out of a traffic ticket",
        "Bad excuses for when you're too hungover to go to work",
        "Bad things to say at the alter",
        "Bad 4-letter words",
        "Unfortunate times to get the squirts",
        "Bad people to name your baby after",
        "Bad occasions to take a selfie",
        "Bad things to wear to a court hearing",
        "Bad occasions to try shrooms for the first time",
        "Bad opening lines on Tinder",
        "Bad Profile Bio lines on Tinder",
        "Bad animals to get as a pet",
        "Bad things to find in your soup",
        "Weird sounds to have as your ringtone",
        "Bad places to ask someone to marry you",
        "People you wouldn't want to play this game with",
        "Bad things to get tattooed on your butt",
        "Bad places to hold a wedding reception",
        "Bad things to have engraved on your tombstone",
        "Bad times to let off a \"silent but deadly\"",
        "Bad places to go on a first date",
        "Bad things to say after a first date"], image: UIImage(named: "bad_categories.png")!)
    
    static let card10 = Card(title: "10) Question Master", rule_description: "\"What's the Question Master?\" For the remainder of the game, The Roller can ask anyone a question. The responder must answer with another question. If they do not, they are subject to the Loser Penalty.", rules: nil, image: UIImage(named: "question_master.png")!)
    
    static let card11 = Card(title: "11) Trivia", rule_description: "Like a depressing Monday night at your local townie bar, it's time for some trivia! The Roller must correctly answer the random trivia question drawn below. Wrong answer = triple the Loser Penalty. All other players may verify the answer via a credible source on the internets.", rules: [
        "Who won the Super Bowl in 2016?",
        "Who won the 2016 College Football National Championship?",
        "Name one common ingredient in beer.",
        "Who won the 1996 Presidential Election?",
        "Approximately how many billion years old is the earth?",
        "Give a scientific explanation of where babies come from.",
        "What movie starred a dog that played basketball?",
        "Name one amendment in the Constitution.",
        "About how many people are alive on the earth right now?",
        "How many continents are there?",
        "Name 3 movies starring Mel Gibson.",
        "Name 3 movies starring Jonah Hill.",
        "Name 2 songs by Rihanna.",
        "What professional baseball team resides in Milwaukee?",
        "Name 1 current pro hockey player.",
        "Name 1 current pro soccer player.",
        "Name the 4 major oceans on planet earth.",
        "Name 1 pro sports team from Canada.",
        "What year did the United States become a country?",
        "What is the official language of the Netherlands?",
        "Name 2 actors from The Fast and The Furious franchise.",
        "Name this movie: \"Sir, can I trouble you for a glass of warm milk? It helps me go to sleep.' 'You can trouble me for a glass of shut-the-hell-up! Now, you will go to sleep or I will PUT you to sleep. Check out the nametag. You're in MY world now, Grandma!\"",
        "Name this movie: \"Mugatu is so hot right now he could take a crap, wrap it in tinfoil, put a couple of fish hooks on it and sell it to Queen Elizabeth as earrings\"",
        "Name this movie: \"I love scotch. Scotchy scotch scotch. Here it goes down, down into my belly\"",
        "Name this movie: \"McLovin? Were you violating that young girl? Were you violating her with your penis?\"",
        "Name this movie: \"Did we just become best friends? YUP! Do you wanna do karate in the garage? YUP!\"",
        "Name this movie: \"I wanna make bank, bro. I wanna drive a Range Rover. I wanna get ass.\"",
        "Name this movie: \"You know how I know you're gay?' 'How?' 'You like Coldplay\"",
        "Name this movie: \"Here's something I would like to remind you two of: our best friend Doug is probably face down in a ditch right now with a meth head butt-fucking his corpse!\"",
        "Name this movie: \"Sometimes my sister, she show her vazhine to my brother Bilo and say 'You will never get dis, you will never get it, la la la la la la!\"",
        "Name this movie: \"I arrived in America's airport with clothings, US Dollars, and a jar of gypsy tears to protect me from AIDS.\"",
        "Name 1 Adam Sandler movie with a Rotten Tomatoes rating above 70%.",
        "Name 4 countries in Africa.",
        "Name 3 cities in New Mexico.",
        "Name 1 character from Game of Thrones.",
        "Name 3 songs by Kanye West.",
        "Name 2 songs by The Beatles.",
        "Name 5 schools in the Big 10",
        "Name 5 schools in the Big 12",
        "Name 5 schools in the ACC",
        "Name 5 schools in the SEC",
        "Name 5 schools in the Pac12",
        "Name 1 pro baseball team whose mascot does not end with the letter \"s\".",
        "Name the last WNBA Champion .",
        "Name 1 WNBA team.",
        "Name this movie: \"If you want the ultimate, you have to be willing to pay the ultimate price.\"",
        "Name this movie: \"If peeing in your pants is cool, consider me Miles Davis.\"",
        "Name this movie: \"That’s what I love about these high school girls, man. I get older, they stay the same age.\"",
        "Name this movie: \"Tigers love pepper. They hate cinnamon.\"",
        "Name this movie: \"How can we be expected to teach children to read...if they can't even fit inside the building!\"",
        "Name this movie: \"Attention campers: Lunch has been cancelled today due to lack of hustle. Deal with it.\"",
        "Name this movie: \"You got a fuckin dart in your neck man!\" \"Y-You're crazy man. You're crazy. I like you...but you're crazy.\"",
        "Name this movie: \"I've got a belly full of white dog crap and now you lay this shit on me?!\"",
        "Name 3 celebrities with a sex tape",
        "Name 3 states weed is legal",
        "Was the dress black and blue or white and gold?",
        "Which month is Black History Month?",], image: UIImage(named: "trivia.png")!)
    
    static let card12 = Card(title: "12) The Cult Leader", rule_description: "All Hail! The Roller is now \"The Cult Leader\" and will read aloud the random cult game drawn below. They may initiate their cult at any time during the remainder of the game. The last one to join the cult is subject to double the Loser Penalty.", rules: [
        "Forehead Master (like Thumb Master but with your head on the table instead of your thumb)",
        "Nap Master (spontaneously lay on the ground)",
        "Slow Clap Master (spontaneously start a slow clap)",
        "Dance Master (spontaneously start dancing)",
        "Standing Master (spontaneously stand up)",
        "Shoes Off Master (spontaneously take your shoes off)",
        "Striptease Master (spontaneously remove an article of clothing)",
        "The Drink Master (spontaneously shout \"Drink, my children\" and everyone must chug/finish their drink)",
        "Viking Master (spontaneously make a horns gesture with your hands on your head and everyone must proceed to pretend to row the Viking ship)",
        "Flex Master (spontaneously start flexing)",
        "Air Guitar Master (spontaneously start playing an imaginary guitar)",
        "Point Master (spontaneously start pointing at someone)",
        "Orgasm Master (spontaneously start making orgasm noises)",
        "Wave Master (spontaneously start the wave)",
        "Raindance Master (spontaneously start doing a tribal rain dance)",
        "Choo-choo Master (spontaneously start making a choo-choo train gesture)",
        "Knock Master (spontaneously start knocking on something)",
        "Jerk-off Master (spontaneously start doing a jerk-off motion)",], image: UIImage(named: "the_cult_leader.png")!)
    
    static let card13 = Card(title: "13) The Most Likely To", rule_description: "Group Game - The Roller will draw a \"Most Likely To\" category below. On the Roller's count of 3, everyone will point to the person who is most likely to do that thing. The person with the most votes is subject to triple the Loser Penalty and definitive proof that they peaked in High School.", rules: [
        "Join a nudist colony",
        "Drive a mini van in 10 years",
        "Fall in love with a waffle house worker",
        "Secretly have their nipples pierced",
        "Regularly eat at Arby's",
        "Hook up with someone at this table tonight",
        "Hook up with a stranger tonight",
        "Start a get rich quick scheme and swindle millions of people",
        "Go to a strip club alone",
        "Join a cult",
        "Start a cult",
        "Own a sex toy",
        "Marry a mail order spouse",
        "Get a face tattoo",
        "Attend a Super Hero convention",
        "Blackout at a work Christmas Party",
        "Makeout with someone twice your age",
        "Attempt to makeout with someone half your age",
        "Fight a stranger for no reason",
        "Become an exotic dancer",
        "Lose their life savings on a gambling bender",
        "Join the mile high club",
        "Spend an evening in jail",
        "Fail a drug test",
        "Become a millionaire and then go bankrupt",
        "Become a bodybuilder",
        "Claim to be a rich doctor in order to get laid",
        "Become a professional wrestler",
        "Marry a professional wrestler",
        "Become President and then get impeached within the first week",
        "Grow sick dreadlocks",
        "Join a biker gang",
        "Stop wearing shoes",
        "Secretly be an alien disguised as a human",
        "Lose their cell phone tonight",
        "Be committed to an insane asylum",
        "Get cold feet at their wedding",
        "Wear a wig in 50 years",
        "Secretly listen to smooth jazz in their car",
        "Regularly eat breakfast at Taco Bell",
        "Get taken out by a professional hitman",
        "Marry me (the person reading this)",
        "Work at Medieval Times",
        "Have recently sent or received a dick pic",
        "Take a boner pill",
        "Take a Dump in the Handicap Stall",
        "Become a drug kingpin",
        "Become a famous magician",
        "Be eaten first if everyone was trapped on a deserted island",
        "Cry tears of joy after making love",
        "Own a sex doll",
        "Wear a t-shirt while swimming at a waterpark",
        "Pee in a public pool",
        "Post a selfie on social media recently",
        "Selfishly cockblock a friend",
        "Live with a bunch of cats later in life",
        "Strike it rich and never talk to anyone at this table again",
        "Act like a dead fish during sex",
        "Be the first person to drink their own urine while lost in the woods",
        "Hook up with me tonight (the person reading this)",
        "Have taken the most V-cards",
        "Have nudes floating around the internet",
        "Catch an STD when they're living in a retirement home",
        "Not be wearing any underwear right now (prove it)",
        "Make out with a distant cousin",
        "Need a liver transplant in the next 10 years",
        "Go to the hospital to retrieve something stuck up their butt",
        "Be mistaken for a member of the opposite sex",
        "Have lost their virginity at the youngest age",
        "Shop for condoms in bulk at Costco",
        "Still join AOL chatrooms",
        "Have a drawer full of expired condoms",
        "Have a secret eHarmony account",
        "Say the word \"Fierce\""], image: UIImage(named: "the_most_likely_to.png")!)
    
    static let card14 = Card(title: "14) The Trolls", rule_description: "Group Game - Everybody listen up! The Roller will open their Instagram and post a comment of a single emoji on a recent pic in their feed (of a non-private account). The Roller will then announce where their post is located and everyone must proceed to post their own comment underneath with nothing but related emojis. The last person to post (and anyone without an Instagram) gets triple the Loser Punishment. Ready, go!", rules: nil, image: UIImage(named: "the_trolls.png")!)
    
    static let card15 = Card(title: "15) Take A Trip", rule_description: "Congratulations! Grab the sunscreen and some lube cuz the Roller just earned an all-inclusive trip to Pen island! (See space Pen15 for your itinerary).", rules: nil, image: UIImage(named: "take_a_trip.png")!)
    
    static let card16 = Card(title: "16) Jail", rule_description: "You have the right to remain silent. Anything you say shall be used against you in the Court of Pen island. Draw below to find out your sentencing.", rules: [
        "You were found guilty of Public Indecency. Lose your dignity, your ability to go within 100 ft of an elementary school, and your next turn.",
        "Your name came up on a suspected terrorist list because you're really bombing this game. You have been deported to Pen island (Pen15).",
        "You paid off the judge with sexual favors. Give the person to your left a massage during their turn and then you may proceed on your next roll.",
        "Your cut-rate lawyer overslept your hearing. Enjoy the Loser Penalty and then draw a sentence again next turn.",
        "You joined a gang while on the inside. You may proceed next turn only after getting a gang sign drawn somewhere on your body.",
        "Your time on the inside has changed you. Give everyone in the game a hug and you may proceed on your next roll.",
        "The person to your left framed you for a heinous crime and you have been sent straight to Pen island (Pen15). You should probably find a way to get your revenge on this two-timing SOB.",
        "You successfully pinned your crime on the person to your left! Switch places with them on the board. On your next turns, they must draw a new Jail sentence while you get to roll from their current spot.",
        "Your lawyer has informed you that the court is very sentimental. If you are able to display a convincing cry while apologizing for something bad you did recently, you may proceed on your next turn.",
        "You managed a prison break! Roll again and proceed.",
        "Ouch! You were shanked by your cell mate. Lay down on the floor while you recover until your next turn, and then you may proceed.",
        "You dropped the soap in the showers. You may proceed on your next turn but cannot make eye contact with anyone until then.",
        "You were caught trying to escape. You have been relocated to maximum security Pen island (Pen15)",
        "You've been awarded a trial by jury! Plead your case about why you should not be banished to Pen island and let the group decide your fate. Guilty = Go to Pen island (Pen15). Not Guilty = Move on next turn.",
        "You've been caught running an elaborate Ponzi scheme in which you swindled every other player in the game out of their life savings. The judge has ruled that if you pay each person $1 (cash or Venmo), you may get out of Jail with no further penalty. If you choose not pay your reparations, you must pay for your crime by going directly to Pen island (Pen15).",
        "You gotta make bail ASAP. If you can convince someone in the game to give you a dollar, you may proceed on your next turn. If your bail is not met, you must go directly to Pen island on your next turn.",
        "The judge found you guilty but let you off easy with community service due to your high probability of becoming someone's bitch on the inside. You must clean all trash off the table prior to your next roll.",
        "Good news, you've been given one phone call! You may call anyone in your phone book, and if they answer, you may move on after your next roll. If they do not answer, you must go directly to Pen island (Pen15).",
        "The detective on your case thinks you're a snake so you've been ordered to take a polygraph test. You have 2 minutes to come up with 2 truths and a lie about anything in your life. Once you have your stories straight, write down the number of your lie on the inside of your hand and tell all 3 stories to the group. Then the group (as a whole) must guess which is your lie. If the group sniffs it out, you go straight to Pen island (Pen15). If you beat the test, you may move on next turn.",
        "You've been offered a plea deal. Tell the court an interesting fact about the last person you hooked up with and you may proceed next turn.",
        "You were caught diddling your cellmate in their sleep late one lonely night. Sickos like you can't be trusted in society so you have been relocated to solitary confinement. Go serve out your sentence of 1 round by sitting down with your nose in the corner of the room.",], image: UIImage(named: "jail.png")!)
    
    static let card17 = Card(title: "17) Human Pictionary", rule_description: "Step 1: Go grab a pen and put 60 seconds on someone's phone timer. Step 2: The Player to the left of The Roller generates a picture theme below (so The Roller can't see) and has 1 minute to draw the image on inside of The Roller's hand. Step 3: Before the timer goes off, The Roller must accurately guess what the image is without laughing. If they laugh or cannot guess it, both participants are subject to double the Loser Penalty. If they guess correctly, the rest of the group is subject to double the Loser Penalty. Hint: it's gonna be dirty.", rules: [
        "Doggy-style",
        "Big Ole' Dildo",
        "Anal Beads",
        "Blue Balls",
        "Sex Swing",
        "Camel Toe",
        "Two Girls, One Cup",
        "Mustache Ride",
        "F.U.P.A.",
        "Man Boobs",
        "The Shocker",
        "Scissoring",
        "Full Bush",
        "Wet Dream",
        "Nip Slip",
        "Dick Pic",
        "Glory Hole",
        "Foot Fetish",
        "MILF",
        "Blow Up Sex Doll",
        "Threesome",
        "Nipple Tassels",
        "Butt Plug",
        "Human Centipede",
        "Golden Shower",
        "Shemale",
        "Boob Job",
        "Crabs",
        "Mangina",
        "Micropenis",
        "Motor Boat",
        "Fish Taco",
        "Manscape",
        "Rim Job",
        "Queef"], image: UIImage(named: "human_pictionary.png")!)
    
    static let card18 = Card(title: "18) Never Have I Ever", rule_description: "Group Game - The Roller will start a game of \"Never Have I Ever\" and then going clockwise, each person at the table will continue it. All players begin with 3 strikes. If you have done said thing, you lose 1 strike. The first person to lose all 3 strikes is subject to triple the Loser Penalty. After one time around the circle, you may take things up a notch and begin drawing from below.", rules: [
        "Received or Given Road Head",
        "Been Tested for STD's",
        "Been Caught Masterbating",
        "Been Caught Having Sex",
        "Used a Sex Toy",
        "Been to a Strip Club",
        "Gone Skinny Dipping",
        "Worked in Fast Food",
        "Eaten at Arby's",
        "Hooked up with a stranger on Spring Break",
        "Gotten Arrested",
        "Gotten busted with a fake ID",
        "Made out with someone with braces",
        "Been in handcuffs",
        "Spent the night in Jail",
        "Been in a fist fight",
        "Found a sex toy in my parent's room",
        "Had my parents find a used condom in my room",
        "Had sex in a roommate's bed",
        "Been injured during sex",
        "Had a strictly friends with benefits relationship that lasted longer than 2 weeks",
        "Blacked out at a family wedding",
        "Thrown up in a taxi",
        "Failed a driving test",
        "Performed oral sex on someone without ever kissing them on the mouth",
        "Called someone the wrong name while hooking up",
        "Required medical attention because there was a foreign object stuck inside me",
        "Received a noise complaint while hooking up",
        "Paid for sex",
        "Had to ask someone whether or not we had sex because I wasn't so sure",
        "Had an STD scare",
        "Had a finger in my ass",
        "Lied about how many people I've hooked up with to avoid judgment",
        "Woken up next to a total stranger",
        "Eaten food off of someone’s naked body",
        "Hooked up with with two different people within twenty-four hours",
        "Had to do the walk of shame",
        "Had sex while someone else watching",
        "Walked in on my parent's",
        "Fantasized about someone in this room",
        "Slept with someone within an hour of meeting them",
        "Hooked up in a public restroom",
        "Been caught throwing a party at my parent's house",
        "Hooked up with someone that didn't speak english",
        "Been caught shoplifting",
        "Been thrown out of a bar",
        "Successfully run away from the cops",
        "Deleted my facebook",
        "Had someone else's pubic hair stuck in my teeth",
        "Had sex in a large body of water",
        "Hooked up with a friend's sibling",
        "Watched porn with someone else",
        "Had to throw away a pair of underwear because of \"an accident\"",
        "Hooked up with a celebrity",
        "Said, \"I'm never drinking again\"",
        "Had my first kiss before age 12",
        "Seen someone in this room naked",
        "Used lube",
        "Given someone a fake phone number",
        "Gone to a foreign country alone",
        "Had plastic surgery",
        "Made a sex tape",
        "Had an ex that now has a kid",
        "Hooked up with a prostitute",
        "Hooked up with someone that weighed significantly more than me",
        "Hooked up with someone I met on Tinder",
        "Milked a cow",
        "Passed gas during oral sex",
        "Carried a condom in my wallet",
        "Been told my junk/boobs were too big to handle",
        "Had two friends fight over me",
        "Cried to get out of a speeding ticket",
        "Hooked up with a co-worker",
        "Had a sexual experience last less than 2 minutes",
        "Crashed a wedding I wasn't invited to",
        "Made out with more than one person at a bar in one night",
        "Been catfished on the internet",
        "Been suspended from school",
        "Been to a nude beach",
        "Had a secret crush on someone in this game",
        "Hooked up with someone with a foot fetish",
        "Paid for porn on the internet",
        "Been on TV",
        "Hooked up with more than 1 person in this game",
        "Hooked up while in the same room as other people also hooking up",
        "Faked an orgasm",
        "Fallen asleep during sex",
        "Attempted to use something other than a condom for protection",
        "Broken the bed during sex",
        "Said \"I love you\" to someone in the last 6 months",
        "Had food licked off my body",
        "Hooked up in a car",
        "Left my underwear in someone's room after hooking up",
        "Been on a blind date",
        "Gone streaking",
        "Regretted hooking up with a close friend of the opposite sex",
        "Left comments on a porn site",
        "Failed a drug test",
        "Done a psychedelic drug",
        "Used a piece of food as a sex toy",
        "Pissed the bed as an adult",
        "Received a booty call from someone in the game",
        "Seen someone in this game naked",
        "Gone to church drunk",
        "Banged someone from Tinder",
        "Ended a night out with a visit to the hospital",
        "Lied about waiting until marriage to have sex",
        "Hooked up in an Uber",
        "Watched porn at work",
        "Shat my pants",
        "Sent a dick pic",
        "Sent a tit pic",
        "Peed in a public shower",
        "Seen 2 girls 1 cup",
        "Been in a threesome",
        "Worn handcuffs",], image: UIImage(named: "never_have_i_ever.png")!)
    
    static let card19 = Card(title: "19) Glamour Shots", rule_description: "Time for some soft smiles. The Roller must allow the Snapchat Paparazzi (and anyone else) to snap a photo while re-enacting the type of picture drawn below. If the photo calls for multiple people, they shall be however many people needed from The Roller's right. Props encouraged.", rules: [
        "Prom Pose (w/ person to roller's right; roller assumes male role)",
        "High School Senior Pic (w/ roller's choice of inspirational quote)",
        "\"We're Engaged!\" Pic (w/ person to roller's right; the roller assume's the role of the ring-wearing fiance)",
        "\"We're having a baby!\" (w/ person to roller's right; pillow stuffed in shirt)",
        "American Gothic (w/ person to roller's right...the game tube makes for a good prop)",
        "Yearbook Portrait (w/ roller's choice of inspirational quote)",
        "\"To Catch a Predator\" Mug Shot",
        "Boy Band Album Cover (minimum 3 members)",
        "Yoga Pose",
        "Riding the Bull (roller assumes role of the bull, rider is person to roller's right)",
        "Boxing Weigh-in (face-to-face matchup w/ person to roller's right)",
        "Sweet Hat (find something in the room that is not a hat to wear on your head)",
        "Sorority Girl (Duck lips, hand on hip, half squat)",
        "The Heisman",
        "Statue of Liberty (the game tube makes a good prop)",
        "Jump Pic (holding hands w/ person to roller's right)",
        "Full Group Selfie",
        "Middle School Slow Dance (w/ person to the roller's right)",
        "Bodybuilder Pose",
        "Hugh Hefner (arms around all members of the opposite sex)",
        "Civil War Commander",
        "Santa Clause (w/ person to roller's right as Santa; roller assumes role of child)"], image: UIImage(named: "glamour_shots.png")!)
    
    static let card20 = Card(title: "20) Distorted Reality", rule_description: "Let's get weird! The Roller will draw a Distorted Reality (i.e. new rule) below. The Roller may enforce this reality for the duration specified. Anyone who breaks from reality is subject to the Loser Penalty.", rules: [
        "All players have T-Rex Arms during this round",
        "All players must shake their jugs when speaking during this round",
        "All players must start every sentence with, \"Shit son,\" during this round",
        "Play the remainder of the game with the lights off",
        "All players must Hashtag their sentence when speaking during this round",
        "All players are only allowed to Soft Smile and may not show their teeth while laughing during this round",
        "The remainder of the game shall be played to old school throwback jams",
        "Choo Choo train - all players must pump their arm up and down like a conductor while anything comes out of their mouth during this round",
        "3rd Person - everyone must refer to themself in 3rd Person during this round",
        "Touchy Feely - everyone must touch the person they are speaking to during this round",
        "No Pointing for the remainder of the game",
        "Kesha rule - you must repeat the last word you say, say (during this round, round)",
        "Everyone must speak in Opera voices during this round",
        "Everyone must do The Wave when a new song comes on for the remainder of the game",
        "Power Hour - Everyone must take a drink when a new song comes on for the remainder of the game",
        "Buffalo/Bull-moose - no one may hold their beverage in their right hand for the remainder of the game",
        "Everyone must refer to the roller as \"Your Highness\" for the remainder of the game",
        "Everyone must compliment someone in the game before rolling the dice for the remainder of the game",
        "Everyone must always be holding Eye Contact with someone else during this round",
        "No blinking allowed during this round",
        "Everyone must use their hand to speak like a Puppeteer during this round",
        "Everyone must have dramatic Soap Opera reactions to everything that is said during this round",
        "Everyone must move in Slow Motion during this round",
        "Everyone must disagree with everything the roller says for the remainder of the game",
        "No walking allowed for the remainder of the game",
        "Only moonwalking allowed for the remainder of the game",
        "Only ice skating allowed for the remainder of the game",
        "Everyone must close 1 eye while speaking during this round",
        "Everyone must do a jerk-off motion after they finish their sentence for the remainder of the game",
        "Everyone must take a drink before they roll the dice for the remainder of the game",
        "Obnoxious Student Section - Everyone must imitate the student section of a basketball game during the next Roller's turn (\"Oooooooooooooooooo!\")",
        "Hodor - The Roller must piggyback anyone that leaves the table to their destination for the remainder of the game",
        "All players must end every sentence with, \"and shit\" during this round (ex. \"I was all eating pancakes and shit\")",
        "High-5's (any time a 5 is rolled everybody High-5 the Roller)",
        "Play the hit song \"Living la Vida Loca\" on repeat during this round",
        "Everyone must start every sentence with \"Suhhh dude\" during this round",
        "Everyone must finish every sentence with \"...My Love\" during this round",], image: UIImage(named: "distorted_reality.png")!)
    
    static let card21 = Card(title: "21) The Wormhole", rule_description: "#Science! The Roller just got sucked through a \"wormhole\" to a random space on the board. Draw below and begin your new life there. ", rules: [
        "11) Trivia",
        "12) The Cult Leader",
        "13) The Most Likely to",
        "14) The Trolls",
        "15) Take a trip",
        "16) Jail",
        "17) Human Pictionary",
        "18) Never Have I Ever",
        "19) Glamour Shots",
        "20) Distorted Reality",
        "22) Admission of Guilt",
        "23) The Prisoner's Dilemma",
        "24) Would you Rather",
        "25) Survivor",
        "26) Text Master",
        "27) Bang, Marry, Kill",
        "28) Accents",
        "29) Lick, Slap, Fondle",
        "Pen15) #PenIsland #Pen15club",
        "Pen15) #PenIsland #Pen15club",
        "Pen16) The Roast",
        "Pen17) Lip Sync Star",
        "Pen18) Mime",
        "Pen19) Oddly Inspirational #TBT",
        "Pen19) Oddly Inspirational #TBT",
        "Pen20) Dare",
        "Pen20) Dare",
        "Pen21) Dancing Fool",
        "Pen22) House Special",
        "Pen23) Emoji Butt Text",
        "Pen23) Emoji Butt Text",
        "Pen24) Quarantine",], image: UIImage(named: "the_wormhole.png")!)
    
    static let card22 = Card(title: "22) Admission of Guilt", rule_description: "Group Game - The Roller will draw an illegal or embarrassing act below. One by one beginning with The Roller, each player must stand up and either confess to the act or plead their innocence. If a player confesses, they're subject to the Loser Penalty. If a player does not confess and another player calls them out with contradictory evidence, they must perform a \"Walk of Atonement\" around the table while saying \"Shame\" repeatedly until their next turn.", rules: [
        "You've been dumped by someone in the past 12 months",
        "You have wildly unmanageable pubic hair",
        "You've stolen a beverage at a fast food restaurant in the past month",
        "You've discreetly passed gas at some point during this game",
        "You've ghosted someone in the past 3 months",
        "You've masterbated in the past 48 hours",
        "You're in the midst of a month (or longer) dry spell",
        "You've had some type of non-necessary plastic surgery",
        "You've tried to find Spring Break pics of someone in the game",
        "You're addicted to tobacco",
        "You would test positive for an illegal substance right now",
        "You would test over the legal limit to drive right now",
        "You're a basic bitch",
        "You've given yourself a below-the-belt haircut this month",
        "You're sexually aroused right now",
        "You've possessed a fake ID at some point in your life",
        "You've cheated on someone in the past 5 years",
        "You still watch MTV",
        "You let your pet Tamagotchi die because you're too selfish to care for others",
        "You illegally watch Netflix/HBO using someone else's account",
        "You collected Pokemon cards as a kid",
        "You've gotten fired from a job",
        "You stole your parent's alcohol in High School",
        "You've recently cried during a movie",
        "You\'ve never voted in an election (because you\'re a lazy turd that hates freedom)",
        "You've fantasized about having a sexual experience with someone in the game",
        "You've flashed someone in order to get something you wanted",
        "You've hooked up in a public bathroom",
        "You've done buttstuff",
        "You've required medical attention because there was a foreign object stuck inside you",
        "You've blown a line of cocaine off of someone else’s body",
        "You've paid to go into the back-room at a strip club",
        "You've slept with someone you knew was in a relationship",
        "You've googled something along the lines of \"STD symptoms\"",
        "You've walked to a park to catch a new Pokemon",
        "You've been drunk at work",
        "You've thrown up at the bar",
        "You've been to a Creed, Nickelback, or Hanson concert",
        "You still have unreturned DVDs from Blockbuster",
        "You once owned a pager",
        "You died of Measles on Oregon Trail like a n00b",
        "You've made yourself a pair of Jorts from cutting jeans",
        "You once had frosted tips, braided cornrows, or a neon-colored highlight in your hair",
        "You once wore puka shells or a stretchy choker necklace",
        "You have worked out in a cut-off sleeveless shirt",
        "You squeeze toothpaste from the middle of the tube like a fucking savage",
        "You've masterbated in someone else's shower or bathtub",
        "You've wiped a booger under a table, desk, or wall",
        "You have a closet full of beanie babies that you think will be worth a fortune one day",
        "You used to rep a fresh pair of JNCO jeans",
        "You put on the Freshman 15 (and never lost it)",
        "You've purposely given someone the wrong name or number after a 1-night stand",
        "You've done a celebratory dab",
        "You've taken a selfie at the gym",
        "You always keep a condom in your wallet or purse \"just in case\"",
        "You've put a Taking Back Sunday lyric as your AIM away message",
        "You have more than 100 unread email notifications on your phone...disgusting",
        "You've filled out a bracket for the Bachelor/Bachelorette",
        "You still tell your friends about how you took State in High School)",], image: UIImage(named: "admission_of_guilt.png")!)
    
    static let card23 = Card(title: "23) The Prisoner's Dilemma", rule_description: "Listen up, this is a simple game but requires a bit of attention. The Roller and player to the Roller's left will stand up to face each other with their right hand behind their back. At the end of a countdown (and without breaking eye-contact), each person will either hold up a peace sign (for \"Peace\"), or hold up their middle finger (for \"Screw\"). If both players choose Peace, each player is only subject to the Loser Penalty. If both players choose Screw, both get popped with 5 TIMES the Loser Penalty. However, if one player chooses Screw while the other player chooses Peace, the Peace player is sent directly to Pen Island (while the Screwer does not have to do anything). 10 second deliberation begins now.", rules: nil, image: UIImage(named: "the_prisoners_dilemma.png")!)
    
    static let card24 = Card(title: "24) Would You Rather", rule_description: "The Roller must answer the \"Would You Rather\" question drawn below. A \"prove it!\" chant from the group is encouraged.", rules: [
        "Motorboat the person on your left for 1 hour or suck on the person to your right's big toe for 10 minutes?",
        "Touch nips with the person on your left for 5 hours or floss with a strand of pubic hair from the person to your right?",
        "Trade genitals with the person to your left or IQ with the person to your right?",
        "Have sex with the person to your left in secret or not have sex with the person to your right, but everyone thinks you did?",
        "Have sex with the person to your left every day for a year or watch the person on your right have sex with your grandma?",
        "Give the person to your left a piggyback ride for a week or get carried around like a baby by the person on your right for a year?",
        "Trade limbs with the person to your left or hair with the person to your right?",
        "Be on the show \"Naked and Afraid\" with the person to your left or your right?",
        "Repopulate the world after a zombie apocalypse with the person to your right or your left?",
        "Hook up with the person on your left or your right?",
        "See the person on your left naked every time you wake up for the rest of your life or be constantly smelling the person to your right's farts for the rest of your life?",
        "Live in a mud hut with the person to your left or a mansion with a waterslide with the person to your right?",
        "Turn into chickens with the person to your left or a turn into goldfish with the person on your left?",
        "Have a pet cat that acts like the person on your left or a pet dog that acts like the person to your right?",
        "Have unlimited pizza with the person to your left or unlimited sex with the person to your right?",
        "Trade bodies with the person to your left or trade heads with the person to your right?",
        "Let the person on your left look through your text history or the person on your right look through your google search history?",
        "Have to share a phone with the person on your left or share a bed with the person on your right?",
        "Only be able to take a bath using the dirty water from the person to your left or be able to take showers but the person on your right is always watching?",
        "Hook up with the opposite gendered version of the person on your left or your right?",
        "Be filthy rich and live with the person to your left or be dead broke and live with the person to your right?",
        "Have a beard made out of the public hair of the person to your left or right?",
        "Have the IQ of the person to your left or the body of the person to your right?",
        "Spend your life as a goldfish with the person on your left or a gerbil with the person on your right?",
        "Get plastic surgery to look like the person to your left or to your right?",
        "Actually hook up with the person on your right but no one knows or have everyone think you hooked up with the person on your left when you actually did not?",
        "Give a sensual back massage to the person to your right or give a half-ass foot massage to the person to your left?",
        "Lick the person to your left from head to toe or kiss the person on your right on the lips?",
        "Get a massage with a happy ending from the person to your left or give a massage with a happy ending to the person to your right?",
        "Shave the entire body of the person to your right or wipe the ass of the person to your left?",
        "Have a 3-some with the 2 players to your left or the 2 players to your right?",
        "Swap heads with the person to your left or bodies with the person to your right?",
        "Be siamese twins with the person to your left or the person to your right?",
        "Swap hair with the person to your left or hands with the person to your right?",
        "Swap voices with the person to your left or torsos with the person to your right?",
        "Never see the person to your left again or see the person to your right 5 times a day for the rest of your life?",
        "Spend a week in jail with the person to your left or accidentally get married in Vegas to the person to your right?",
        "Have to kiss the person to your left good night for the rest of your life or kiss the person to your right good morning for the rest of your life?",
        "Wear a sweater made from the person to your left's head hair (with no undershirt) or socks made from the person to your right's pubic hair?",
        "Have the person to your left's voice or the person to your right's hands?",
        "Get a visible neck tattoo with the name of the person to your left or a back tattoo with a full-size face of the person to your right?",
        "Feed a starving African child you will never see, or own an actual working light saber?",
        "Speak like Yoda or Breathe like Darth Vader?",
        "Legally change your last name to Hitler or switch lives with the person to your left?",
        "Get an atomic wedgie from the person to your left or get a swirly from the person to your right?",
        "Fuck a goat but you're the only person that knows or not fuck a goat but everyone you know thinks you did?",
        "Fight 4 foot tall John Cena or 8 foot tall Megan Fox?",
        "Bang Kate Upton with a Penis or Dwayne 'The Rock' Johnson with a vagina?",
        "Have to see clouds of everyone's farts or have to smell everyone's digestive tract?",
        "Watch your parents have sex every day for the rest of your life or join in once to stop it?",
        "Cannonball into a pool of lava or be flattened like a pancake by a steam roller?"], image: UIImage(named: "would_you_rather.png")!)
    
    static let card25 = Card(title: "25) Survivor", rule_description: "It's like that show that was cool 15 years ago, except the exact opposite (you do not want to be stuck on this island). One by one starting with The Roller, everyone will vote on one person to be exiled to the beginning of Pen island. The person with the most votes must pack their bags. Present your vote as if you are dramatically displaying a hand-written card to the group.", rules: nil, image: UIImage(named: "survivor.png")!)
    
    static let card26 = Card(title: "26) The Text Master", rule_description: "All phones go on the table face up with the ringer turned on. For the remainder of the game, The Roller is now the Text Master and may respond to all incoming texts...'Send Nudes' anyone?", rules: nil, image: UIImage(named: "the_text_master.png")!)
    
    static let card27 = Card(title: "27) Bang, Marry, Kill", rule_description: "The Roller must decide who they would Bang, Marry, or Kill from the 3 players on their left. Loser Penalty to all participants, because let's be honest--everyone's a loser in this game.", rules: nil, image: UIImage(named: "bang_marry_kill.png")!)
    
    static let card28 = Card(title: "28) Accents", rule_description: "It's time for some blatantly racist stereotypes! The Roller will make up or draw a random Accent below that the group must speak in for the remainder of the game. Loser Penalty for all who speak out of this new tongue.", rules:
        ["Steve Irwin, Crocodile Hunter (\"Ah, crikey mate!\")",
        "Wise Chinaman (\"Confucious say, good fortune come from cookie\")",
        "Southern Hick (\"Reckon a storm's a brewin down yonder\")",
        "Polite Brit (\"I do beg your pardon good sir?\")",
        "Arnold Schwarzenegger (\"Hasta la vista, baby\")",
        "Christian Bale Batman (\"Be the hero Pen island needs, not the hero it deserves.\")",
        "Caveman (\"Me take drink. Me thirsty.\")",
        "Hillbilly (\"I don't talk too good\")",
        "Borat (\"Very Nice!\")",
        "New Yorker (\"Aye, bada bing bada boom!\")",
        "Jamaican (\"Yeah mon!\")",
        "Irish (\"Top o' the mornin' to ya lassie!\")",
        "Mexican (\"Si, si!\")",
        "Indian (\"Thank you, come again!\")",
        "Teenage Girl (\"Like, totes IDK just whatev\")",
        "Italian (\"Ayyyyy! Itsa pizzaa pie!, Itsa me, a Mario!\")",
        "Michael Jackson (\"That's ignorant. Eee-hee!\")",
        "Yoda (\"Talk like this, you must\")",
        "Canadian (\"Let's just go play some hockey, eh?\")",], image: UIImage(named: "accents.png")!)
    
    static let card29 = Card(title: "29) Lick, Slap, Fondle", rule_description: "As if things couldn't get any weirder, it's about to go to the next level. The Roller must Lick, Slap, or Fondle the 3 players to their left. Roller's choice of who gets what.", rules: nil, image: UIImage(named: "lick_slap_fondle.png")!)
    
    static let card30 = Card(title: "30) Go Back 15 Spaces", rule_description: "Aw, so close! The Roller must move backward 15 spaces.", rules: nil, image: UIImage(named: "go_back_15_spaces.png")!)
    
    static let card31 = Card(title: "Pen15) #Penisland #Pen15club", rule_description: "Upon arrival on beautiful Pen island, you are required to join the exclusive \"Pen15 Club\" (this means 'Pen15' is written on your hand in case you lived under a rock in elementary school). The person to the Roller's right may do the honors at the size of their discretion. Proof of membership must be submitted on the social media of their choice by snapping a photo of their hand and posting with the caption \"#PenIsland #Pen15club\"", rules: nil, image: UIImage(named: "penisland_pen15club.png")!)
    
    static let card32 = Card(title: "Pen16) The Roast", rule_description: "Beginning with the person to the left, everyone must insult The Roller. 1 Loser Penalty to ease the pain of every sick burn received. Finish every insult with an enthusiastic \"Boom, roasted.\"", rules: nil, image: UIImage(named: "the_roast.png")!)
    
    static let card33 = Card(title: "Pen17) Lip Sync Star", rule_description: "The Roller must perform 30 seconds of a concert quality lip sync show from the next song chosen by whoever's in charge of the music. Channel that inner Beyonce! ", rules: nil, image: UIImage(named: "lip_sync_star.png")!)
    
    static let card34 = Card(title: "Pen18) Mime", rule_description: "Just shut your face. The Roller is not allowed to speak for the remainder of their time on the island. Instead, they must mime what they are trying to say. Loser Penalty for every word spoken.", rules: nil, image: UIImage(named: "mime.png")!)
    
    static let card35 = Card(title: "Pen19) Oddly Inspirational", rule_description: "Everyone is so hashtag blessed for getting to witness this gem. The Roller must Instagram (or Facebook) the oldest picture stored in their phone's camera roll. They must caption the post with the inspirational quote generated below followed by \"#TBT #PenIslandInspiration\". Get ready to inspire some Likes!", rules: [
        "\"Sing like no one is listening. Love like you've never been hurt. Dance like nobody is watching.\"",
        "\"Live. Laugh. Love.\"",
        "\"You are never too old to set another goal or dream a new dream.\"",
        "\"If you can dream it, you can do it.\"",
        "\"Shoot for the moon, for even if you miss you will land amongst the stars.\"",
        "\"You have to learn the rules of the game. And then you have to play better than anyone else.\"",
        "\"Try to be a rainbow in someone's cloud.\"",
        "\"Nothing is impossible, the word itself says 'I'm possible'!\"",
        "\"You miss 100% of the shots you don't take.\"",
        "\"It's not the number of breaths we take, but the number of moments that take our breath away.\"",
        "\"Life is what happens to you while you're busy making other plans.\"",
        "\"You're only as strong as the drinks you mix, the tables you dance on, and the friends you party with\"",
        "\"Live for the nights you'll never remember with the friends you'll never forget\"",
        "\"You have to look through the rain to see the rainbow.\"",
        "\"Yesterday is history, tomorrow a mystery and today is a gift. That's why we call it the present.\"",
        "\"You have to kiss a lot of frogs before you find your prince.\"",
        "\"Everything happens for a reason.\"",
        "\"If life gives you lemons, make lemonade.\"",
        "\"It takes more muscles to frown than it does to smile.\"",
        "\"Life is not about waiting for the storm to pass. It's about learning to dance in the rain.\"",
        "\"You only live once.\"",
        "\"Make America Great Again\"",
        "\"As we go on, we remember, all the times we, had together\" - Vita Mansee, 1999",
        "\"Don't go chasing waterfalls, Please stick to the rivers and the lakes that you're used to\" - Destin E. Child, 1994",
        "\"I get knocked down, but I get up again, you're never gonna keep me down\" - Chum B. Wumba, 1997"], image: UIImage(named: "oddly_inspirational.png")!)
    
    static let card36 = Card(title: "Pen20) Dare", rule_description: "Truth or Dare? Just kidding, everyone knows you're lame so the choice has been made for you. The Roller must fulfill a Dare drawn below. The game shall not proceed until completed.", rules: [
        "Post a Selfie Mirror Profile Pic on Facebook",
        "Wrap yourself in toilet paper like a mummy",
        "Get a lower back tattoo drawn on by the person to your left",
        "Storytell your last BM",
        "Facetime your mom",
        "Text your ex the \"Crying Jordan\" meme",
        "Call the person you last texted. You may only speak in questions and you may not be the person to end the conversation.",
        "Show everyone your undies",
        "Lick three different things around you",
        "Text a number 1 digit away from your own asking if they'd like to be \"Text Pals\"",
        "Take a Semi-Nude Lap around the house",
        "Play one legit spin of Spin the Bottle (or Spin the Phone)",
        "Tweet #gettinghydratedonpenisland",
        "Tell the story of losing your virginity",
        "Tell the story of your worst hookup experience",
        "Tell the story of the dumbest thing you ever did while drinking",
        "Tell the story of the worst trouble you ever got in in school",
        "Retweet Donald Trump's latest tweet",
        "Retweet Hillary Clinton's latest tweet",
        "Knock on one of your neighbors door and ask if you can borrow a cup of sugar",
        "Do a snow angel on the ground during the next song",
        "Go to the bathroom and turn your pants or shirt inside out",
        "Read your most recent text conversation to the group while doing a full impersonation of the person on the other side of the text",
        "Show everyone your 5 most recent pictures on your phone",
        "Read your last 10 searches from your phone's browser history",
        "Power-rank everyone in the game according to who you'd most like to hook up with",
        "Change your FB profile pic to a picture of Donald Trump",
        "Sit on each person's lap as they roll the dice for one round",
        "Friend the first 5 people that show up on the \"People You May Know\" feed on Facebook",
        "Go outside to the porch/balcony/front yard and yell at the top of your lungs \"I AM A GOLDEN GOD!\"",
        "Trade 3 articles of clothing with the person to your right",
        "Slow dance to 30 seconds of a Nickelback song with the person on your right",
        "Have someone draw \"THUG LIFE\" on your knuckles",
        "Take a group picture of all the players, #hashtag it with the top trending #hashtag at the moment on either Facebook/Twitter/Instagram",
        "Send a group message to 3 unrelated members of the opposite sex \"Hey, you up?\"",
        "Demonstrate your favorite sex position with a player of your choosing",
        "Have an imaginary bloody sword fight with the person on your left, resulting in a dramatic death - Snapchat encouraged",], image: UIImage(named: "dare.png")!)
    
    static let card37 = Card(title: "Pen21) Dancing Fool", rule_description: "Dance like no one is watching. Except everyone is. And you're going to look stupid. The Roller must dance alone continuously until their next turn.", rules: nil, image: UIImage(named: "dancing_fool.png")!)
    
    static let card38 = Card(title: "Pen22) House Special", rule_description: "The Owner of the game has the honors of concocting a shot for The Roller using anything in the kitchen (FDA approved). Bon Appetit!", rules: nil, image: UIImage(named: "house_special.png")!)
    
    static let card39 = Card(title: "Pen23) Emoji Butt Text", rule_description: "The Roller must open their Text Messages app and scroll all the way to the bottom of their history. When they arrive at the very first message (to another human), they must \"Accidentally\" send a single emoji text to this person and re-awaken a conversation that's probably been dead since 2009. \"Is it too late now to say sorry?\"", rules: nil, image: UIImage(named: "emoji_butt_text.png")!)
    
    static let card40 = Card(title: "Pen24) Quarantine", rule_description: "Turns out those weren't WORRY warts after all! You've contracted a vile disease on Pen island and must be quarantined. Go sit under the nearest table or in the corner of the room until your next turn.", rules: nil, image: UIImage(named: "quarantine.png")!)
    
    static let allCards = [CardManager.card1, CardManager.card2, CardManager.card3, CardManager.card4,CardManager.card5, CardManager.card6, CardManager.card7, CardManager.card8, CardManager.card9, CardManager.card10, CardManager.card11, CardManager.card12, CardManager.card13, CardManager.card14, CardManager.card15, CardManager.card16, CardManager.card17, CardManager.card18, CardManager.card19, CardManager.card20, CardManager.card21, CardManager.card22, CardManager.card23, CardManager.card24, CardManager.card25, CardManager.card26, CardManager.card27, CardManager.card28, CardManager.card29, CardManager.card30, CardManager.card31, CardManager.card32, CardManager.card33, CardManager.card34, CardManager.card35, CardManager.card36, CardManager.card37, CardManager.card38, CardManager.card39, CardManager.card40,]
}
