//
//  CardManager.swift
//  Penisland
//
//  Created by Dan Patey on 5/26/16.
//  Copyright © 2016 Dan Patey. All rights reserved.
//

import Foundation
class CardManager: NSObject {
    
    static let card1 = Card(title: "1) The Toast", rule_description: "\"Cheers to the last time we will all be friends.\" The Roller must start the game off by proposing a group toast.", rules: nil)
    
    static let card2 = Card(title: "2) Name Master", rule_description: "The Roller must assign each player with a new name (or draw random below) to replace all your lame and worn-out birthnames. The Roller may enforce these names for the remainder of the game by handing out the Loser Penalty to anyone who forgets to use them."
        , rules: [
            "Everyone is \"Peasant\"",
            "Everyone is \"Vin Diesel\"",
            "Everyone is a type of Jungle Animal (as determined by the Name Master)",
            "Everyone is a different Reality TV Star. Go around the circle to introduce yourselves.",
            "Everyone is a Past President. Go around the circle to introduce yourselves.",
            "Everyone must take the name of the person to their left",
            "Everyone must take the name of their first pet. Go around the circle to introduce yourselves.",
            "Everyone is \"Bro\"/\"Lady Bro\"",
            "Everyone is \"Mr.\" / \"Miss\" plus their First Name (example: Mr. Billy)",
            "Everyone is \"Senior\" / \"Seniorita\" & their Last Name (example: Seniorita Johnson)",
            "Everyone is a different Fast Food Chain (examples: \"Wendy\", \"Carl Jr.\", \"Burger King\"). Go around the circle to introduce yourselves.",
            "Everyone is \"Chief\"",
            "All guys are \"Daddy\"; All girls are \"Mama\"",
            "Everyone is \"Sweetie\"",
            "Everyone is \"Sugar-tits\"",
            "The Name Master must give everyone a stripper name",
            "Everyone is the name of their sexiest body part (as determined by the Name Master)",
            "Everyone is \"Lil\" plus their first name (example: Lil Steve)",
            "Everyone is \"Big\" plus their first name (example: Big Tina)",
            "Everyone is \"Fat\" plus their first name (example: Fat Tiffany)",
            "Everyone is \"Sir\" / \"Madam\" plus their first name and their birthplace (example: Sir Tobin of Omaha). Go around the circle to introduce yourselves.",
            "Everyone is \"Dr.\" plus their last name",
            "Everyone is \"Your Honor\"",
            "Everyone is a Little Rascal (Alfalfa, Spanky, Darla, Porky, Froggy, Uh-huh, Waldo, Buckwheat)"])
    
    static let card3 = Card(title: "3) Date", rule_description: "OMG love is in the air! The Roller must choose a \"date\" of the opposite sex (if applicable). Whenever one person drinks, so must the other. If another player in the game catches one of the tandem not drinking when they are supposed to, both players shall get double the Loser Penalty. Make sure everyone makes things extra uncomfortable by coming to unfounded conclusions as to why this person was chosen."
        , rules: nil)
    
    static let card4 = Card(title: "4) Beverage Butler", rule_description: "Just like in one of them super fancy restaurants that give you free bread and cloth napkins, The Roller must provide all players with beverages when ordered for the remainder of the game. If non-compliant, the Beverage Butler shall be banished from the game forever. No tips required.", rules: nil)
    
    static let card5 = Card(title: "5) President Trump", rule_description: "While completely unqualified, The Roller is now the President of the game. This means they have the power to over-rule the Loser Penalty for all group-based games and hand out whatever they see fit. They will also resolve any and all disputes. President Trump may appoint a Vice President to aid in decision making. Prepare yourselves for a long game with this asshole.", rules: nil)
    
    static let card6 = Card(title: "6) Snapchat Paparazzi", rule_description: "The Roller must secretly capture their opponents doing something weird on Snapchat at some point during the game (there should be plenty of opportunities). If you're the type of person that doesn't have a Snapchat, you can simply go get your photos developed at the local pharmacy after the game and then mail them out to every contact in your phonebook. Just be sure to include an airtight contract that the photos must be destroyed after 24 hours so nothing scandalous winds up in the tabloids.", rules: nil)
    
    static let card7 = Card(title: "7) The Gamble", rule_description: "The Roller and another player in the game (Roller's choice) must make a handshake wager of $2 on who will finish the game first. \"No Cash\" = No Excuse (Venmo that bish #penislandgamble)", rules: nil)
    
    static let card8 = Card(title: "8) Make A Rule", rule_description: "The Roller must make a rule in which all players must follow. Like a madman drunk on power, they may ruthlessly enforce this rule for the remainder of the game by handing out the Loser Penalty to anyone that breaks it.", rules: nil)
    
    static let card9 = Card(title: "9) Tunes Master", rule_description: "Sorry guys, like a cut-rate wedding DJ you hired off craigslist, The Roller gets to impose their shitty music on you for the remainder of the game (Just know that if it gets too bad there are Pen Island playlists available on Spotify).", rules: nil)
    
    static let card10 = Card(title: "10) Bad Categories", rule_description: "Group Game - The Roller must draw a random Bad Category below. Beginning with person to The Roller's left, all players must say a relevant answer. No repeats. 1st player to mess up is subject to double the Loser Penalty.", rules: nil)
    
    static let card11 = Card(title: "11) Question Master", rule_description: "\"I'm Ron Burgundy?\" For the remainder of the game, The Roller can ask anyone a question. The responder must answer with another question. If they do not, they are subject to the Loser Penalty.", rules: nil)
    
    static let card12 = Card(title: "12) Trivia", rule_description: "Like a depressing Monday night at your local townie bar, it's time for some trivia! The Roller must correctly answer the random trivia question drawn below. Wrong answer = triple the Loser Penalty. All other players may verify the answer via a credible source on the internets.", rules: [
        "Who won the Super Bowl in 2016?",
        "Who won the 2016 College Football National Championship?",
        "Name one common ingredient in beer.",
        "Who won the 1996 Presidential Election?",
        "Approximately how many billion years old is the earth?",
        "Where do babies come from?",
        "What movie starred a dog that played basketball?",
        "What animal does Veal come from?",
        "What is the capital of Florida?",
        "What is the capital of Texas?",
        "What is the capital of California?",
        "What is the capital of New York?",
        "Name one amendment in the Constitution.",
        "About how many people are alive on the earth right now?",
        "How many continents are there?",
        "Name 3 movies starring Mel Gipson.",
        "Name 3 movies starring Jonah Hill.",
        "Name 1 song by Rhianna.",
        "What professional baseball team resides in Milwaukee?",
        "Name 1 current pro hockey player.",
        "Name 1 current pro soccer player.",
        "Name the 4 major oceans on planet earth.",
        "Name 1 pro sports team in Kansas.",
        "Name 1 pro sports team from Canada.",
        "Name 1 pro sports team in North Carolina.",
        "What year did the United States become a country?",
        "What is the official language of the Netherlands?",
        "Name 2 actors from The Fast and The Furious franchise.",
        "Name this movie: \"Sir, can I trouble you for a glass of warm milk? It helps me go to sleep.' 'You can trouble me for a glass of shut-the-hell-up! Now, you will go to sleep or I will PUT you to sleep. Check out the nametag. You're in MY world now, Grandma!\"",
        "Name this movie: \"Magatu is so hot right now he could take a crap, wrap it in tinfoil, put a couple of fish hooks on it and sell it to Queen Elizabeth as earrings\"",
        "Name this movie: \"I love scotch. Scotchy scotch scotch. Here it goes down, down into my belly\"",
        "Name this movie: \"McLovin? Were you violating that young girl? Were you violating her with your penis?\"",
        "Name this movie: \"Did we just become best friends? YUP! Do you wanna do karate in the garage? YUP!\"",
        "Name this movie: \"I wanna make bank, bro. I wanna drive a Range Rover. I wanna get ass.\"",
        "Name this movie: \"You know how I know you're gay?' 'How?' 'You like Coldplay\"",
        "Name this movie: \"Here's something I would like to remind you two of: our best friend Doug is probably face down in a ditch right now with a meth head butt-fucking his corpse!\"",
        "Name this movie: \"Sometimes my sister, she show her vazhine to my brother Bilo and say 'You will never get dis, you will never get it, la la la la la la!\"",
        "Name this movie: \"I arrived in America's airport with clothings, US Dollars, and a jar of gypsy tears to protect me from AIDS.\"",
        "Name 1 Adam Sandler movie with a Rotten Tomatoes rating above 60%.",
        "Name 4 countries in Africa.",
        "Name 3 cities in New Mexico.",
        "Name 1 character from Game of Thrones (first and last name).",
        "Name 3 songs by Kanye West.",
        "Name 2 songs by The Beatles.",
        "Name 5 schools in the Big 10",
        "Name 5 schools in the Big 12",
        "Name 5 schools in the ACC",
        "Name 5 schools in the SEC",
        "Name 5 schools in the Pac12",
        "Name 1 pro baseball team who's mascot does not end with the letter \"s\"",
        "Name the last WNBA Champion",
        "Name 1 WMBA team"])
    
    static let card13 = Card(title: "13) The Cult Leader", rule_description: "All Hail! The Roller is now \"The Cult Leader\" and must read aloud the random cult game drawn below. The Cult Leader may initiate his cult at any time during the remainder of the game. The last one to join the cult is subject to double the Loser Penalty.", rules: [
        "Thumb Master (thumb on the table)",
        "Forehead Master (like thumb master but with your head on the table instead)",
        "Nap Master (lay on the ground)",
        "Slow Clap Master (start a slow clap)",
        "Dance Master (start dancing)",
        "Standing Master (stand up)",
        "Shoes Off Master (take your shoes off)",
        "Stripper Master (remove an article of clothing)",
        "The Drink Master (shout \"Drink, my children\" and chug/finish your drink)",
        "Viking Master (Make a horns gesture with your hands on your head and everyone has to pretend to row the Viking ship)",
        "Flex Master (start flexing)",
        "Air Guitar Master (start playing an imaginary guitar)",
        "Point Master (start pointing at someone)",
        "Orgasm Master (start making orgasm noises)",
        "Wave Master (start the wave)",
        "Medusa Master (point to anyone you want to turn them to stone, release them when you're ready)"])
    
    static let card14 = Card(title: "14) The Sneaky Texter", rule_description: "The Roller now has the ability to text anyone in the game, at any time, a number from 1-5. If a person receives one of these messages from the Sneaky Texter, they are subject to the Loser Penalty times the number received in the text. However, if the Sneaky Texter is caught in the act of texting by any player in the game, they are immediately subject to triple the Loser Penalty. Everyone should constantly have their eye on this fast-fingered weasel.", rules: nil)
    
    static let card15 = Card(title: "15) The Most Likely To", rule_description: "Group Game - The Roller draws a \"Most Likely to\" category below. On the Roller's count of 3, everyone points to the person who is most likely to do that thing. The person with the most votes is subject to triple the Loser Penalty and definitive proof that they peaked in High School.", rules: [
        "Join a nudist colony",
        "Drive a mini van in 10 years",
        "Fall in love with a waffle house worker",
        "Secretly have their nipples pierced",
        "Eat at Arby's",
        "Hook up with someone at this table tonight",
        "Hook up with a stranger tonight",
        "Start a get rich quick scheme and swindle millions of people",
        "Go to a strip club alone",
        "Join a cult",
        "Start a cult",
        "Own a sex toy",
        "Marry a mail order spouse",
        "Get a face tattoo",
        "Attend a Furry convention",
        "Blackout at a work Christmas Party",
        "Makeout with someone twice your age",
        "Attempt to makeout with someone half your age",
        "Fight a stranger for no reason",
        "Become an exotic dancer",
        "Lose their life savings on a gambling bender",
        "Join the mile high club",
        "Spend an evening in jail",
        "Fail a drug test",
        "Become a millionare and then go bankrupt",
        "Become a body builder",
        "Claim to be a rich doctor in order to get laid",
        "Become a professional wrestler",
        "Marry a professional wrestler",
        "Run for president, win, then get impeached within the first week",
        "Grow sick dreadlocks",
        "Join a biker gang",
        "Stop wearing shoes",
        "Secretly be an alien disguised as a human",
        "Lose their cell phone tonight",
        "Be committed to an insane asylum",
        "Get cold feet at their wedding",
        "Wear a wig in 50 years",
        "Secretly listen to smooth jazz in their car",
        "Eat breakfast at Taco Bell",
        "Get taken out by a professional hitman",
        "Marry me (the reader)",
        "Work at Medieval Times",
        "Have recently sent or received a dick pic",
        "Take a boner pill",
        "Take a Dump in the Handicap Stall",
        "Become a drug kingpin",
        "Become a magician",
        "Be eaten first if everyone was trapped on a deserted island",
        "Cry tears of joy after making love",
        "Own a sex doll",
        "Wear a t-shirt while swimming at a waterpark",
        "Pee in the pool",
        "Post a recent selfie on social media",
        "Cockblock a friend",
        "Live with a bunch of cats later in life",
        "Strike it rich and never talk to anyone at this table again",
        "Act like a dead fish during sex",
        "Be the first person to drink their own urine while lost in the woods",
        "Hook up with me tonight (the reader)",
        "Have taken the most V-cards",
        "Have nudes floating around the internet",
        "Catch an STD when they're living in a retirement home",
        "Not be wearing any underwear right now (prove it)",
        "Make out with a distant cousin",
        "Need a liver transplant in the next 10 years",
        "Go to the hospital to retrieve something stuck up their butt",
        "Be mistaken for a member of the opposite sex",
        "Have lost their virginity at the youngest age",
        "Shop for condoms in bulk at Costco",
        "Still have an AIM account",
        "Post something on social media with the hashtag #freethenipple",
        "Have a drawer full of expired condoms"])
    
    static let card16 = Card(title: "16) The Trolls", rule_description: "Group Game - Everybody listen up! The Roller must open their Instagram and post a comment of a single emoji on a recent pic in their feed. The Roller will then announce where their post is located and everyone must proceed to post their own comment underneath with nothing but related emojis. The last person to post (and anyone without an Instagram) gets triple the Loser Punishment. Ready, go!", rules: nil)
    
    static let card17 = Card(title: "17) Take A Trip", rule_description: "Congratulations! Grab the sunscreen and some lube cuz the Roller just earned an all-inclusive trip to Pen island! (See square 17P for your itinerary).", rules: nil)
    
    static let card18 = Card(title: "18) Jail", rule_description: "You have the right to remain silent. Anything you say shall be used against you in the Court of Pen island. Draw below to find out your sentencing.", rules: [
    "You were found guilty of Public Indecency. Lose your dignity, your ability to go within 100 ft of an elementary school, and your next turn.",
    "Your name came up on a suspected terrorist list because you're really bombing this game. You have been deported to Pen island (17P).",
    "You paid off the judge with sexual favors. Give the person to your left a massage during their turn and then you may proceed on your next roll.",
    "Your cut-rate lawyer overslept your hearing. Enjoy the Loser Penalty and then draw again next turn.",
    "You joined a gang while on the inside. You may proceed next turn only after getting a gang sign drawn somewhere on your body.",
    "Your time on the inside has changed you. Give everyone in the game a hug upon your release prior to your next roll.",
    "The person to your left framed you for a heinous crime and you have been sent straight to Pen island (17P). You should probably find a way to get your revenge on this two-timing SOB.",
    "You successfully pinned your crime on the person to your right! Switch places with them on the board. On your next turns, they must draw a new Jail sentence while you get to roll from their current spot.",
    "Your lawyer has informed you that the court is very sentimental. If you are able to display a convincing cry while apologizing for something bad you did recently, you may proceed on your next turn.",
    "You managed a prison break! Roll again and proceed.",
    "Ouch! You were shanked by your cell mate. Skip your next turn while you recover, and then you may proceed.",
    "You dropped the soap in the showers. You may proceed on your next turn but cannot make eye contact with anyone until then.",
    "You were caught trying to escape. You have been relocated to maximum security Pen island (17P)",
    "You've been awarded a trial by jury! Plead your case about why you should not be banished to Pen island and let the group decide your fate. Guilty = Go to Pen island (17P). Not Guilty = Move on next turn.",
    "You've been caught running an elaborate Ponzi scheme in which you swindled every other player in the game out of their life savings. The judge has ruled that if you pay each person $1 (cash or Venmo), you may get out of Jail with no further penalty. If you choose not pay your reparations, you must pay for your crime by going directly to Pen island (17P).",
    "You gotta make bail ASAP. If you can convince someone in the game to give you a dollar, you may proceed on your next turn. If your bail is not met, you must go directly to Pen island on your next turn.",
    "The judge found you guilty but let you off easy with community service due to your high probability of becoming someone's bitch on the inside. You must clean all trash off the table prior to your next roll.",
    "Good news, you've been given one phone call! You may call anyone in your phone book, and if they answer, you may move on after your next roll. If they do not answer, you must go directly to Pen island (17P). Choose wisely!",
    "The detective on your case thinks you're a snake so you've been ordered to take a polygraph test. You have 2 minutes to come up with 2 truths and a lie about anything in your life. Once you have your stories straight, write down the number of your lie on the inside of your hand and tell them to the group. Then the group (as a whole) must guess which is your lie. If the group sniffs it out, go straight to Pen island (17P). If you beat the test, you may move on next turn. Hope you got a good poker face.",
    "You've been offered a plee deal. Tell the court the last person you hooked up with and finish your drink. It's better than a life sentance. Proceed next turn. "])
    
    static let card19 = Card(title: "19) Human Pictionary", rule_description: "First things first, go grab a pen and put 60 seconds on someone's phone timer. Then the Player to the left of The Roller generates a picture theme below (so The Roller can't see) and has 1 minute to draw the image on inside of The Roller's hand. Before the timer goes off, The Roller must accurately guess what the image is without laughing. If they laugh or cannot guess it, both participants are subject to double the Loser Penalty. If they guess correctly, the rest of the group is subject to double the Loser Penalty. Hint: it's gonna be dirty.", rules: [
        "Doggy-style",
        "Big Ole' Dildo",
        "Anal Beads",
        "Blue Balls",
        "Sex Swing",
        "Camel Toe",
        "Two Girls, One Cup",
        "Mustache Ride",
        "F.U.P.A.",
        "Man Boobs",
        "The Shocker",
        "Scissoring",
        "Full Bush",
        "Wet Dream",
        "Nip Slip",
        "Dick Pic",
        "Glory Hole",
        "Foot Fetish",
        "MILF",
        "Blow Up Doll",
        "Threesome",
        "Nipple Tassels",
        "Butt Plug",
        "Human Centipede",
        "Golden Shower",
        "Shemale",
        "Boob Job",
        "Crabs (Pubic)",
        "Mangina",
        "Micropenis",
        "Motor Boat",
        "Fish Taco",
        "Manscape",
        "Rim Job"])
    
    static let card20 = Card(title: "20) Bust A Rhyme", rule_description: "Group Game - The Roller says a word (or draws below). Beginning with person to The Roller's left, all players must respond with another word that rhymes. No repeats. 1st person to break the rhyme streak gets double the Loser Penalty. If you say \"orange\", just leave and never return.", rules: ["Luck", "Knit", "Sock", "Shoe", "Ham", "Glass", "Sink", "Bunt", "Duck", "Art"])
    
    static let card21 = Card(title: "21) Never Have I Ever", rule_description: "Time for some soft smiles. The Roller must allow the Snapchat Paparazzi (and anyone else) to snap a photo while re-enacting the type of picture drawn below. If the photo calls for multiple people, they shall be however many people needed from The Roller's left. Props encouraged.", rules: [
        "Received/Given Road Head",
        "Been Tested for STD's",
        "Been Caught Masterbating",
        "Been Caught Having Sex",
        "Used a Sex Toy",
        "Been to a Strip Club",
        "Gone Skinny Dipping",
        "Worked in Fast Food",
        "Eaten at Arby's",
        "Hooked up with a stranger on Spring Break",
        "Gotten Arrested",
        "Gotten busted with a fake ID",
        "Made out with someone with braces",
        "Been in handcuffs",
        "Spent the night in Jail",
        "Been in a fist fight",
        "Found a sex toy in my parent's room",
        "Had my parents find a used condom in my room",
        "Had sex in a roommate's bed",
        "Been injured during sex",
        "Had a strictly friends with benefits relationship that lasted longer than 2 weeks",
        "Blacked out at a family wedding",
        "Thrown up in a taxi",
        "Failed a driving test",
        "Performed oral sex on someone without ever kissing them on the mouth",
        "Called someone the wrong name while hooking up",
        "Required medical attention because there was a foreign object stuck inside me",
        "Received a noise complaint while hooking up",
        "Paid for sex",
        "Had to ask someone whether or not we had sex because I wasn’t so sure",
        "Had an STD scare",
        "Had a finger in my ass",
        "Lied about how many people I've hooked up with to avoid judgment",
        "Woken up next to a total stranger",
        "Eaten food off of someone’s naked body",
        "Hooked up with with two different people within twenty-four hours",
        "Had to do the walk of shame",
        "Had sex while someone else watching",
        "Walked in on my parent's",
        "Fantasized about someone in this room",
        "Slept with someone within an hour of meeting them",
        "Hooked up in a public restroom",
        "Been caught throwing a party at my parent's house",
        "Hooked up with someone that didn't speak english",
        "Been caught shoplifting",
        "Been thrown out of a bar",
        "Successfully run away from the cops",
        "Deleted my facebook",
        "Had someone else's pubic hair stuck in my teeth",
        "Had sex in a large body of water",
        "Hooked up with a friend's sibling",
        "Watched porn with someone else",
        "Had to throw away a pair of underwear because of \"an accident\"",
        "Hooked up with a celebrity",
        "Said, \"I'm never drinking again\"",
        "Had my first kiss before age 12",
        "Seen someone in this room naked",
        "Used lube",
        "Given someone a fake phone number",
        "Gone to a foreign country alone",
        "Had plastic surgery",
        "Made a sex tape",
        "Had an ex that now has a kid",
        "Hooked up with a prostitute",
        "Hooked up with someone that weighed significantly more than me",
        "Hooked up with someone I met on Tinder",
        "Milked a cow",
        "Passed gas during oral sex",
        "Carried a condom in my wallet",
        "Been told my junk/boobs were too big to handle",
        "Had two friends fight over me",
        "Cried to get out of a speeding ticket",
        "Hooked up with a co-worker",
        "Had a sexual experience last less than 2 minutes",
        "Crashed a wedding I wasn't invited to",
        "Made out with more than one person at a bar in one night",
        "Been catfished on the internet",
        "Been suspended from school",
        "Been to a nude beach",
        "Had a secret crush on someone in this game",
        "Hooked up with someone with a foot fetish",
        "Paid for porn on the internet",
        "Been on TV",
        "Hooked up with more than 1 person in this game",
        "Hooked up while in the same room as other people also hooking up",
        "Faked an orgasm",
        "Fallen asleep during sex",
        "Attempted to use something other than a condom for protection",
        "Broken the bed during sex",
        "Said \"I love you\" to someone in the last 6 months",
        "Had food licked off my body",
        "Hooked up in a car",
        "Left my underwear in someone's room after hooking up",
        "Been on a blind date",
        "Gone streaking",
        "Regretted hooking up with a close friend of the opposite sex",
        "Left comments on a porn site",
        "Failed a drug test",
        "Done a psychodelic drug",
        "Used a piece of food as a sex toy",
        "Pissed the bed as an adult",
        "Received a booty call from someone in the game",
        "Seen someone in this game naked",
        "Gone to church drunk",
        "Banged someone from Tinder",
        "Ended a night out with a visit to the hospital",
        "Lied about waiting until marriage to have sex",
        "Hooked up in an Uber",
        "Watched porn at work",
        "Shat my pants",
        "Sent a dick pic",
        "Sent a tit pic"])
    
    static let card22 = Card(title: "22) Glamour Shots", rule_description: "Time for some soft smiles. The Roller must allow the Snapchat Paparazzi (and anyone else) to snap a photo while re-enacting the type of picture drawn below. If the photo calls for multiple people, they shall be however many people needed from The Roller's left. Props encouraged.", rules: [
        "Prom Pose (roller assumes male role)",
        "High School Senior Pic",
        "\"We're Engaged!\" Pic (w/ person to your left)",
        "\"We're having a baby!\" (w/ person to roller's left; pillow stuffed in shirt)",
        "American Gothic (w/ person to left)",
        "Yearbook Portrait",
        "Mug Shot",
        "Boy Band Album Cover (minimum 3 members)",
        "Yoga Pose",
        "Riding the Bull (roller assumes role of the bull)",
        "Boxing Weigh-in (face-to-face matchup w/ person to roller's left)",
        "Sweet Hat (find something in the room that is not a hat to wear on your head)",
        "Sorority Girl (Duck lips, hand on hip, arched back)",
        "Heisman dat hoe",
        "Statue of Liberty (you represent freedom in the Western Hemisphere, show the world)"])
    
    static let card23 = Card(title: "23) Distorted Reality", rule_description: "Let's get weird! The Roller draws a Distorted Reality (i.e. new rule) below. The Roller must enforce this reality for the duration specified. Anyone who breaks from reality is subject to the Loser Penalty.", rules: [
        "All players have T-Rex Arms during this round",
        "All players must shake their jugs when speaking during this round",
        "All players must start every sentence with, \"Shit son,\" during this round",
        "Play the remainder of the game with the lights out",
        "All players must Hash-tag their sentence when speaking during this round",
        "All players are only allowed to Soft Smile and may not show their teeth while laughing during this round",
        "The remainder of the game shall be played to throwback jams",
        "Choo Choo train - all players must pump their arm up and down like a conductor while anything comes out of their mouth during this round",
        "3rd Person - everyone must refer to themself in 3rd Person during this round",
        "Touchy Feely - everyone must touch the person they are speaking to during this round",
        "No Pointing for the remainder of the game",
        "Kesha rule - you must repeat the last word you say, say (during this round, round)",
        "Everyone must speak in Opera voices during this round",
        "Everyone must do The Wave when a new song comes on for the remainder of the game",
        "Power Hour - Everyone must take a drink when a new song comes on for the remainder of the game",
        "Buffalo/Bull-moose - no one may use their right hand to drink for the remainder of the game",
        "Everyone must refer to the roller as \"Your Highness\" for the remainder of the game",
        "Everyone must compliment someone in the game before rolling the dice for the remainder of the game",
        "Harlem Globetrotters - everyone must pass around an imaginary basketball to the next player when their turn is over",
        "Everyone must always be holding Eye Contact with someone else during this round",
        "No blinking allowed during this round",
        "Everyone must use their hand to speak like a Puppeteer during this round",
        "Everyone must have Soap Opera Reactions to everything said during this round",
        "Everyone must move in Slow Motion during this round",
        "Everyone must disagree with everything the roller says for the remainder of the game",
        "No walking allowed for the remainder of the game",
        "Only moonwalking allowed for the remainder of the game",
        "Only iceskating allowed for the remainder of the game",
        "Everyone must close 1 eye while speaking during this round",
        "Everyone must do a jerk-off motion after they finish their sentence for the remainder of the game",
        "Everyone must drink before they roll the dice for the remainder of the game",
        "Obnoxious Student Section - Everyone must immitate the student section of a basketball game as each person rolls the dice turn during this round (\"Oooooooooooooooooo!\")",
        "Everyone must take a small chug prior to their roll this round",
        "Hodor - The Roller must piggyback anyone that leaves the table to their destination for the remainder of the game",
        "All players must end every sentance with, \" 'n shit\" during this round (\"I was all eating pancakes 'n shit\")",
        "High 5s (any time a 5 is rolled everybody high 5 the roller)"])
    
    static let card24 = Card(title: "24) The Wormhole", rule_description: "Hope you got your spacesuit on! Just like Interstellar Matthew McConaughey, the Roller got sucked through a \"wormhole\" to a random space on the board. Draw below and begin your new life there. #physics", rules: nil)
    
    static let card25 = Card(title: "25) Drink Discrimination", rule_description: "Group Game - The Roller draws a characteristic below. Everyone that it describes is subject to double the Loser Penalty.", rules: [
        "You identify as a female gendered",
        "You identify as male gendered",
        "You're a virgin",
        "You're not a virgin",
        "You're attracted to someone in the game",
        "You're in a relationship with someone in the game",
        "You were born in a different state or country",
        "Your hair color is not natural",
        "You've had something medically implanted inside your body",
        "You were born in the 90's",
        "You were born in the 80's",
        "You smoke cigarettes",
        "You would test positive for an illegal substance",
        "You're sober",
        "You're not sober",
        "You're drinking beer",
        "You're drinking something other than beer",
        "You're an only child",
        "Your ancestors were immigrants",
        "You're currently in last place",
        "You're a basic bitch",
        "You ask for a water cup at a fast food restaurant and sneakily fill it with soda",
        "You've masterbated this week",
        "You're wearing pants",
        "You've gone to the bathroom since the beginning of this game",
        "You're going out after this",
        "You took an uber to get here",
        "You went to highschool with someone in the game",
        "You've given yourself a below-the-belt haircut this week",
        "You're in the midst of a month or longer dry spell",
        "You've been on a first date this month",
        "You're sexually aroused right now",
        "You're currently holding a cell phone in your hand",
        "You're next to someone who is \"literally, the worst\"",
        "You're better looking than the person to your left",
        "You're better looking than the person to your right",
        "You're the tallest person in the game",
        "You're the shortest person in the game",
        "You have a dating app on your phone",
        "You literally can't even"])
    
    static let card26 = Card(title: "26) Waterfall", rule_description: "Group Game - The Roller begins a drinking waterfall. This means you drink until the person to your right stops drinking. Be on the lookout for THAT GUY who is just pretending to drink because the cold is burning his throat. He's among you.", rules: nil)
    
    static let card27 = Card(title: "27) Would You Rather", rule_description: "The Roller must answer the \"Would You Rather\" question drawn below. A \"prove it!\" chant from the group is encouraged.", rules: [
        "Motorboat the person on your left for 1 hour or suck on the person to your right's big toe for 10 minutes?",
        "Touch nips with the person on your left for 5 hours or floss with a strand of pubic hair from the person to your right?",
        "Trade genitals with the person to your left or IQ with the person to your right?",
        "Have sex with the person to your left in secret or not have sex with the person to your right, but everyone thinks you did?",
        "Have sex with the person to your left every day for a year or watch the person on your right have sex with your grandma?",
        "Give the person to your left a piggyback ride for a week or get carried around like a baby by the person on your right for a year?",
        "Trade limbs with the person to your left or hair with the person to your right?",
        "Be on the show \"Naked and Afraid\" with the person to your left or your right?",
        "Repopulate the world after a zombie apocolypse with the person to your right or your left?",
        "Hook up with the person on your left or your right?",
        "See the person on your left naked every time you wake up for the rest of your life or be constantly smelling the person to your right's farts for the rest of your life?",
        "Live in a mud hut with the person to your left or a mansion with a waterslide with the person to your right?",
        "Turn into chickens with the person to your left or a turn into goldfish with the person on your left?",
        "Have a pet cat that acts like the person on your left or a pet dog that acts like the person to your right?",
        "Have unlimited pizza with the person to your left or unlimited sex with the person to your right?",
        "Trade bodies with the person to your left or trade heads with the person to your right?",
        "Let the person on your left look through your text history or the person on your right look through your google search history?",
        "Have to share a phone with the person on your left or share a bed with the person on your right?",
        "Only be able to take a bath using the dirty water from the person to your left or be able to take showers but the perosn on your right is always watching?",
        "Hook up with the opposite gendered version of the person on your left or your right?",
        "Be filthy rich and live with the person to your left or be dead broke and live with the person to your right?",
        "Have a beard made out of the public hair of the person to your left or right?",
        "Have the IQ of the person to your left or the body of the person to your right?",
        "Spend your life as a goldfish with the person on your left or a gerbil with the person on your right?",
        "Get plastic surgery to look like the person to your left or to your right?",
        "Actually hook up with the person on your right but no one knows or have everyone think your hooked up with the person on your left when you actually did not?",
        "Give a sensual back massage to the person to your right or give a half-ass foot massage to the person to your left?",
        "Lick the person to your left from head to toe or kiss the person on your right on the lips?",
        "Get a massage with a happy ending from the person to your left or give a massage with a happy ending to the person to your right?",
        "Shave the entire body of the person to your right or wipe the ass of the person to your left?",
        "Have a 3-some with the 2 players to your left or the 2 players to your right?",
        "Swap heads with the person to your left or bodies with the person to your right?",
        "Be siamese twins with the person to your left or the person to your right?",
        "Swap hair with the person to your left or hands with the person to your right?",
        "Swap voices with the person to your left or torsos with the person to your right?",
        "Never see the person to your left again or see the person to your right 5 times a day for the rest of your life?",
        "Spend a week in jail with the person to your left or accidentally get married in Vegas to the person to your right?",
        "Have to kiss the person to your left good night for the rest of your life or kiss the person to your right good morning for the rest of your life?",
        "Wear a sweater made from the person to your left's head hair (with no undershirt) or socks made from the person to your right's pubic hair?",
        "Have the person to your left's voice or the person to your right's hands?",
        "Get a visible neck tattoo with the name of the person to your left or a back tattoo with a full-size face of the person to your right?",
        "Feed a starving African child you will never see, or own an actual working light saber",
        "Speak like Yoda or Breathe like Darth Vader",
        "Legally change your last name to Hitler or switch lives with the person to your left",
        "Get an atomic wedgie or get a swirly",
        "Fuck a goat and you're the only person that knows you did or not fuck a goat but everyone you know thinks you did",
        "Fight 4 foot tall John Cena or 8 foot tall Megan Fox",
        "Bang Kate Upton with a Penis or Dwayne 'The Rock' Johnson with a vagina",
        "Be able to see everyones farts or see an image of the last poop each person has had when you meet them",
        "Watch your parents have sex every day for the rest of your life or join in once to stop it"])
    
    static let card28 = Card(title: "28) Survivor", rule_description: "It's like that show that was cool 15 years ago, except the exact opposite (you do not want to be stuck on this island). One by one starting with The Roller, everyone must vote on one person to be exciled to the beginning of Pen island (doesn't matter where they currently are). Present your vote as if you are dramatically displaying a hand-written card to the group.", rules: nil)
    
    static let card29 = Card(title: "29) The Text Master", rule_description: "All phones go on the table face up with the ringer turned on. For the remainder of the game, The Roller is now the Text Master and may respond to any incoming texts that they see. \"Send Nudes\"", rules: nil)
    
    static let card30 = Card(title: "30) Accents", rule_description: "Blatantly racist stereotype time! The Roller must make up or draw a random Accent below that the group must speak in for the remainder of the game. Loser Penalty for all who speak out of this new tongue.", rules:
        ["Australian (Throw another shrimp on the barbie mate!)",
         "Chinese (Ching chang chong)",
         "Southern Hick (Reckon a storm's a brewin down yonder)",
         "British (I do beg your pardon good sir?)",
         "German (Sprechen ze Deutch?)",
         "Batman (Be the hero this game needs, not the hero it deserves.)",
         "Caveman (Me take drink. Me thirsty.)",
         "Hillbilly (I don't talk too good)",
         "Borat (Very Nice!)",
         "New Yorker (Aye, bada bing bada boom!)",
         "Jamaican (Yeah mon!)",
         "Irish (Top o' the mornin' to ya lassie!)",
         "Mexican (Si, si!)",
         "Indian (Thank you, come again!)",
         "Teenage Girl (Like, totes IDK)",
         "Italian (ayyyyy! Itsa pizzaa pie!, Itsa me, Mario!)",])
    
    static let card31 = Card(title: "31) The Drinker's Dilemma", rule_description: "Listen up, this game is simple but requires a bit of attention. The Roller and player to the Roller's left stand up and face each other with their right hand behind their back. At the end of a countdown (and without breaking eye-contact), each person will either hold up a peace sign (\"Peace\"), or hold up their middle finger (\"Screw\"). If both players choose Peace, each player is only subject to the Loser Penalty. If both players choose Screw, both players get 5 times the Loser Penalty. However, if one player chooses Screw while the other player chooses Peace, the Peace player is sent directly to Pen Island (while the Screwer does not have to do anything). 10 second deliberation begins now - 10, 9, 8, 7, 6, 5, 4, 3, 2, 1", rules: nil)
    
    static let card32 = Card(title: "32) Bang, Marry, Kill", rule_description: "This will be awkward no matter how strategic you think you are. The Roller must decide who they would Bang, Marry, or Kill from the 3 players on their left.", rules: nil)
    
    static let card33 = Card(title: "33) Lick, Slap, Fondle", rule_description: "As if things couldn't get any weirder, it's about to go to the next level. The Roller must Lick, Slap, or Fondle the 3 players to their left. Roller's choice of who gets what, though everyone's a loser in this game.", rules: nil)
    
    static let card34 = Card(title: "34) Go Back 17 Spaces", rule_description: "Aw, so close! The Roller must move back 17 spaces.", rules: nil)
    
    static let card35 = Card(title: "17P) #Penisland #Pen15club", rule_description: "Upon arrival on beautiful Pen island, you must become an official member of the exclusive \"Pen15 Club\" (this means 'Pen15' is written on your hand in case you lived under a rock in elementary school). The person to the left of The Roller may do the honors at the size of their discretion. Proof of your membership must be submitted on the social media of your choice by snapping a photo of your hand with the caption \"#PenIsland #Pen15club\".", rules: nil)
    
    static let card36 = Card(title: "18P) The Roast", rule_description: "Beginning with the person to the left, everyone must insult The Roller. 1 Loser Penalty to ease the pain of every sick burn. Boom, roasted.", rules: nil)
    
    static let card37 = Card(title: "19P) Lip Sync Star", rule_description: "Time to channel your inner Beyonce. The Roller must perform 30 seconds of a concert quality lip sync performance from the next song chosen by whoever's in charge of the music.", rules: nil)
    
    static let card38 = Card(title: "20P) Mime", rule_description: "Just shut your face. The Roller is not allowed to speak for the remainder of their time on the island. Instead, they must mime what they are trying to say. Loser Penalty for every word spoken.", rules: nil)
    
    static let card39 = Card(title: "21P) Oddly Inspirational", rule_description: "Everyone is so hashtag blessed for getting to witness this gem. The Roller must Instagram (or Facebook) the oldest picture stored in their phone's camera roll. They must caption the post with the inspirational quote generated below followed by \"#TBT #PenIslandInspiration\". Get ready to inspire some Likes!", rules: [
        "\"Sing like no one is listening. Love like you've never been hurt. Dance like nobody is watching.\"",
        "\"Live. Laugh. Love.\"",
        "\"You are never too old to set another goal or dream a new dream.\"",
        "\"If you can dream it, you can do it.\"",
        "\"Shoot for the moon, for even if you miss you will land amongst the stars.\"",
        "\"You have to learn the rules of the game. And then you have to play better than anyone else.\"",
        "\"Try to be a rainbow in someone's cloud.\"",
        "\"Nothing is impossible, the word itself says 'I'm possible'!\"",
        "\"You miss 100% of the shots you don't take.\"",
        "\"It's not the number of breaths we take, but the number of moments that take our breath away.\"",
        "\"Life is what happens to you while you're busy making other plans.\"",
        "\"You're only as strong as the drinks you mix, the tables you dance on, and the friends you party with\"",
        "\"Live for the nights you'll never remember with the friends you'll never forget\"",
        "\"You have to look through the rain to see the rainbow.\"",
        "\"Yesterday is history, tomorrow a mystery and today is a gift. That's why we call it the present.\"",
        "\"You have to kiss a lot of frogs before you find your prince.\"",
        "\"Everything happens for a reason.\"",
        "\"If life gives you lemons, make lemonade.\"",
        "\"It takes more muscles to frown than it does to smile.\"",
        "\"Life is not about waiting for the storm to pass. It's about learning to dance in the rain.\"",
        "\"You only live once.\"",
        "\"Make America Great Again\"",
        "\"As we go on, we remember, all the times we, had together\" - Vita Mansee, 1999",
        "\"Don't go chasing waterfalls, Please stick to the rivers and the lakes that you're used to\" - Destin E. Child, 1994",
        "\"I get knocked down, but I get up again, you're never gonna keep me down\" - Chum B. Wumba, 1997"])
    
    static let card40 = Card(title: "22P) Dare", rule_description: "Truth or Dare? Just kidding, we all know you're lame so we made the choice for you. The Roller must fulfill a Dare drawn below. The game shall not proceed until completed.", rules: [
        "Post a Mirror Selfie Profile Pic on Facebook",
        "Wrap yourself in toilet paper like a mummy",
        "Get a lower back tattoo drawn on by the person to your left",
        "Storytell your last BM",
        "Facetime your mom",
        "Text your ex the \"Crying Jordan\" meme",
        "Call the person you last texted. You may only speak in questions and you may not be the person to end the conversation.",
        "Show everyone your undies",
        "Lick three different things around you",
        "Text a number 1 digit away from your own asking if they'd like to be text pals",
        "Take a Semi-Nude Lap around the house",
        "Play one spin of Spin the Bottle (or Spin the Phone)",
        "Tweet #gettinghydratedonpenisland",
        "Tell the story of losing your virginity",
        "Tell the story of your worst hookup experience",
        "Tell the story of the dumbest thing you ever did while drinking",
        "Tell the story of the worst trouble you ever got in in school",
        "Retweet Donald Trump's latest tweet",
        "Retweet Hilary Clinton's latest tweet",
        "Knock on one of your neighbors door and ask if you can borrow a cup of sugar",
        "Do a snow angel on the ground during the next song",
        "Go to the bathroom and turn your pants or shirt inside out",
        "Read your most recent text conversation to the group while doing a full impersonation of the person on the other side of the text",
        "Show everyone your 5 most recent pictures on your phone",
        "Read your last 10 searches from your phone's browser history",
        "Power-rank everyone in the game according to who you'd most like to hook up with",
        "Change your FB profile pic to a picture of Donald Trump",
        "Sit on each person in the game's lap as they roll the dice for one round",
        "Friend the first 5 people that show up on the \"People You May Know\" feed on Facebook",
        "Go outside to the porch/balcony/front yard and yell at the top of your lungs \"I AM A GOLDEN GOD!\"",
        "Trade 3 articles of clothing with the person to your right",
        "Slow dance to 30 seconds of a Nickelback song with the person on your left "])
    
    static let card41 = Card(title: "23P) Dancing Fool", rule_description: "Dance like no one is watching. Except everyone is. And you're going to look stupid. The Roller must dance alone continuously until their next turn.", rules: nil)
    
    static let card42 = Card(title: "24P) House Special", rule_description: "The Owner of the game gets to concoct a shot for The Roller using anything in the kitchen (FDA approved). Bon Appetit!", rules: nil)
    
    static let card43 = Card(title: "25P) Emoji Butt Text", rule_description: "The Roller must open their Text Messages app and scroll all the way to the bottom of their history. When they arrive at the very first message (to another human), they must \"Accidentally\" send a single emoji text to this person and re-awaken a conversation that's probably been dead since 2009. \"Is it too late now to say sorry?\"", rules: nil)
    
    static let card44 = Card(title: "26P) Quarrantine", rule_description: "Turns out those weren't WORRY warts after all! You've contracted a vile disease on Pen island and must be quarrantined. Go sit on the floor under the nearest table or in the corner of the room until your next turn.", rules: nil)
    
    static let allCards = [CardManager.card1, CardManager.card2, CardManager.card3, CardManager.card4,CardManager.card5, CardManager.card6, CardManager.card7, CardManager.card8, CardManager.card9, CardManager.card10, CardManager.card11, CardManager.card12, CardManager.card13, CardManager.card14, CardManager.card15, CardManager.card16, CardManager.card17, CardManager.card18, CardManager.card19, CardManager.card20, CardManager.card21, CardManager.card22, CardManager.card23, CardManager.card24, CardManager.card25, CardManager.card26, CardManager.card27, CardManager.card28, CardManager.card29, CardManager.card30, CardManager.card31, CardManager.card32, CardManager.card33, CardManager.card34, CardManager.card35, CardManager.card36, CardManager.card37, CardManager.card38, CardManager.card39, CardManager.card40, CardManager.card41, CardManager.card42, CardManager.card43, CardManager.card44]
}